image: node:latest

stages:
  - lint

eslint:
  stage: lint
  script:
    - npm install
    - npx eslint --fix --ignore-pattern 'assets/bootstrap-min.js' --ignore-pattern 'assets/minisearch-min.js' .
