image: node:latest

# stages:
#   - lint
#   - test

# eslint:
#   stage: lint
#   script:
#     - npm install
#     - npx eslint --fix .

test:
  cache:
    paths:
      - node_modules/
  variables:
    CI: "true"
  before_script:
    - echo "checking node version"
    - node -v
    - echo "installing dependencies..."
    - npm install
  script:
    - npm test tests/import_export.test.js